### ISSUE TITLE
doesnt execute code?

### ISSUE THREAD

**Issue by TheSmugGod** [bcl-team/bcl-runcode#2]
![image](https://github.com/bcl-team/bcl-runcode/assets/123635357/de311ddc-7eb8-4929-91f5-e6473a5df37d)

**Comment by ivanzaida** [comment]
Hi! Thanks for the report.
Could you please be more specific with the reproduction steps?
I just tested and cannot achieve the reesult you've provided on the screenshot.

**Comment by ivanzaida** [comment]
@TheSmugGod 
this [commint](https://github.com/bcl-team/bcl-runcode/commit/4e9f03d97ee4f125230b65fa104928d76958a461) should have fixed your issue, please verify
